# ReHybrid-Mount
#
# SPDX-License-Identifier: GPL-3.0-only

[workspace]
members = ["xtask", "tools/notify"]
resolver = "2"

[package]
name = "hybrid-mount"
version = "6.0.0"
edition = "2024"
description = "ReHybrid-Mount: from-scratch rebuild of Hybrid Mount for KernelSU"
license = "GPL-3.0-only"
repository = "https://github.com/Hybrid-Mount/meta-hybrid_mount"
publish = false

[dependencies]
flate2 = "1"
fs_ext4 = {
    package = "am-fs-ext4",
    git = "https://github.com/Hybrid-Mount/rust-fs-ext4.git",
    rev = "d4e01155c2fc6b0dcc143220e8dc7e62d65cff51",
    version = "0.4.0",
}
getrandom = "0.3"
hex = "0.4"
libc = "0.2"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "1"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15"

[target.'cfg(unix)'.dependencies]
extattr = "1"

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
ksu = { git = "https://github.com/Tools-cx-app/ksu.git", version = "0.2.0" }
loopdev = { git = "https://github.com/Hybrid-Mount/loopdev.git", version = "0.5.0" }
procfs = "0.18"
rustix = { version = "1.1.4", features = ["fs", "mount"] }
