# Copyright (C) 2026 YuzakiKokuban <heibanbaize@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

inlineHeader = """
Copyright (C) {{props["year"]}} {{props["owner"]}}
SPDX-License-Identifier: GPL-3.0-only
"""

[properties]
year = 2026
owner = "YuzakiKokuban <heibanbaize@gmail.com>"
