# Copyright (C) 2026 YuzakiKokuban <heibanbaize@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

headerPath = "LICENCE_HEADER"
excludes = ["webui/**"]

[properties]
year = 2026
owner = "YuzakiKokuban <heibanbaize@gmail.com>"

[mapping.SCRIPT_STYLE]
extensions = ["rule"]
