# Copyright (C) 2026 YuzakiKokuban <heibanbaize@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

[toolchain]
channel = "nightly-2026-08-10"
components = ["rustfmt", "clippy"]
targets = ["aarch64-linux-android"]
profile = "minimal"
