/*
 * Copyright (C) 2026 YuzakiKokuban <heibanbaize@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generated by scripts/generate-info-tab-data.mjs
 * Generated at: 2026-07-22T05:07:38.965Z
 */

import type { InfoTabSection } from "./infoTabData";

export const INFO_TAB_SECTIONS: InfoTabSection[] = [
  {
    id: "core",
    label: "Hybrid Mount",
    repoDisplayName: "Hybrid-Mount/meta-hybrid_mount",
    repoUrl: "https://github.com/Hybrid-Mount/meta-hybrid_mount",
    contributors: [
      {
        login: "YuzakiKokuban",
        avatar_url: "https://avatars.githubusercontent.com/u/94628337?v=4",
        html_url: "https://github.com/YuzakiKokuban",
        type: "User",
        url: "https://api.github.com/users/YuzakiKokuban",
        name: "由崎黑板",
        bio: "就是一个普通的小孩，喜欢玩点酷酷的东西",
      },
      {
        login: "Tools-cx-app",
        avatar_url: "https://avatars.githubusercontent.com/u/127004703?v=4",
        html_url: "https://github.com/Tools-cx-app",
        type: "User",
        url: "https://api.github.com/users/Tools-cx-app",
        name: "生于生时 亡于亡刻",
        bio: "",
      },
      {
        login: "Anatdx",
        avatar_url: "https://avatars.githubusercontent.com/u/10851902?v=4",
        html_url: "https://github.com/Anatdx",
        type: "User",
        url: "https://api.github.com/users/Anatdx",
        name: "Anan",
        bio: "わがはいは…夏目アンアン、である。",
      },
      {
        login: "947409161",
        avatar_url: "https://avatars.githubusercontent.com/u/127842603?v=4",
        html_url: "https://github.com/947409161",
        type: "User",
        url: "https://api.github.com/users/947409161",
        name: "知秋",
        bio: "",
      },
      {
        login: "lizehui2025",
        avatar_url: "https://avatars.githubusercontent.com/u/221314267?v=4",
        html_url: "https://github.com/lizehui2025",
        type: "User",
        url: "https://api.github.com/users/lizehui2025",
        name: "Imagining_Time_and_Space",
        bio: "",
      },
      {
        login: "backslashxx",
        avatar_url: "https://avatars.githubusercontent.com/u/118538522?v=4",
        html_url: "https://github.com/backslashxx",
        type: "User",
        url: "https://api.github.com/users/backslashxx",
        name: "backslashxx",
        bio: "",
      },
      {
        login: "ThePrimalPea",
        avatar_url: "https://avatars.githubusercontent.com/u/92656767?v=4",
        html_url: "https://github.com/ThePrimalPea",
        type: "User",
        url: "https://api.github.com/users/ThePrimalPea",
        name: "The Primal Pea",
        bio: "Save the Lawnrunners",
      },
      {
        login: "AlexLiuDev233",
        avatar_url: "https://avatars.githubusercontent.com/u/102930921?v=4",
        html_url: "https://github.com/AlexLiuDev233",
        type: "User",
        url: "https://api.github.com/users/AlexLiuDev233",
        name: "AlexLiuDev233",
        bio: "",
      },
      {
        login: "Koch2333",
        avatar_url: "https://avatars.githubusercontent.com/u/54238405?v=4",
        html_url: "https://github.com/Koch2333",
        type: "User",
        url: "https://api.github.com/users/Koch2333",
        name: "Koch2333",
        bio: "Do I also have to coding?",
      },
      {
        login: "UlasuNoka",
        avatar_url: "https://avatars.githubusercontent.com/u/211364601?v=4",
        html_url: "https://github.com/UlasuNoka",
        type: "User",
        url: "https://api.github.com/users/UlasuNoka",
        name: "UlasuNoka",
        bio: "↑ ↑ ↓ ↓ ← → ← → B A",
      },
      {
        login: "lamprose",
        avatar_url: "https://avatars.githubusercontent.com/u/29279979?v=4",
        html_url: "https://github.com/lamprose",
        type: "User",
        url: "https://api.github.com/users/lamprose",
        name: "Michelle Rodriguez",
        bio: "Hi, I'm Michelle Rodriguez, a diligent student aspiring to become a successful lawyer someday. I love reading books and debating with peers.",
      },
      {
        login: "geniucker-dev",
        avatar_url: "https://avatars.githubusercontent.com/u/165345526?v=4",
        html_url: "https://github.com/geniucker-dev",
        type: "User",
        url: "https://api.github.com/users/geniucker-dev",
        name: "Geniucker Zhu",
        bio: "@IDO-Lab | EE @ ZJU-UIUC",
      },
      {
        login: "MasFha",
        avatar_url: "https://avatars.githubusercontent.com/u/140007137?v=4",
        html_url: "https://github.com/MasFha",
        type: "User",
        url: "https://api.github.com/users/MasFha",
        name: "MasFha",
        bio: "",
      },
      {
        login: "pkczc",
        avatar_url: "https://avatars.githubusercontent.com/u/154660013?v=4",
        html_url: "https://github.com/pkczc",
        type: "User",
        url: "https://api.github.com/users/pkczc",
        name: "pkczc",
        bio: "",
      },
    ],
  },
];
